language: python
python:
  - '3.8'

# safelist
branches:
  only:
    - dev

before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=purbeurre_project.settings.travis

script:
  - python manage.py test
